//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class region_setting
    {
        public int RegionID { get; set; }
        public Nullable<int> WashID { get; set; }
        public Nullable<int> RentID { get; set; }
        public Nullable<int> SettleDay { get; set; }
        public Nullable<int> SettleType { get; set; }
        public Nullable<double> MatchNumber { get; set; }
        public Nullable<double> LimitNumber { get; set; }
        public int CreateUserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<double> Integral { get; set; }
        public Nullable<short> PaymentMode { get; set; }
        public Nullable<double> Deposit { get; set; }
        public Nullable<short> RentPaymentMode { get; set; }
        public Nullable<System.DateTime> WashingTime { get; set; }
        public Nullable<System.DateTime> RentTime { get; set; }
    }
}
