//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class businessinvoice
    {
        public string BID { get; set; }
        public int HotelID { get; set; }
        public string BNo { get; set; }
        public short InvType { get; set; }
        public Nullable<short> SubType { get; set; }
        public string Note { get; set; }
        public short Stated { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> ReviewTime { get; set; }
        public Nullable<int> ReviewUserID { get; set; }
        public Nullable<System.DateTime> CloseTime { get; set; }
        public Nullable<int> CloseUserID { get; set; }
        public Nullable<System.DateTime> ExecTime { get; set; }
    }
}
