//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods
    {
        public int ID { get; set; }
        public string GoodsName { get; set; }
        public int CateID { get; set; }
        public string GoodsLogo { get; set; }
        public decimal GoodsMoney { get; set; }
        public decimal CostPrice { get; set; }
        public string UnitName { get; set; }
        public string Remarks { get; set; }
        public bool Grounding { get; set; }
        public int Sort { get; set; }
        public int Hoting { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public bool Deleted { get; set; }
    }
}
