//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_detail
    {
        public int ID { get; set; }
        public int HotelID { get; set; }
        public string Slogan { get; set; }
        public string Logo { get; set; }
        public string HotelName { get; set; }
        public string HotelPoint { get; set; }
        public string HotelProfile { get; set; }
        public string HotelTel { get; set; }
        public string HotelImg { get; set; }
    }
}
