//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicelogdetail
    {
        public int ID { get; set; }
        public string LogID { get; set; }
        public string ColumnName { get; set; }
        public string ColumnText { get; set; }
        public string PrimaryKeyColName { get; set; }
        public string PrimaryKeyValue { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string CreateType { get; set; }
    }
}
