//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicedetail
    {
        public int ID { get; set; }
        public string InvNo { get; set; }
        public string InvID { get; set; }
        public short InvType { get; set; }
        public short DataType { get; set; }
        public Nullable<short> InvSubType { get; set; }
        public int HotelID { get; set; }
        public int RegionID { get; set; }
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int SizeID { get; set; }
        public string SizeName { get; set; }
        public int TextileCount { get; set; }
        public System.DateTime InvCreateTime { get; set; }
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public Nullable<decimal> WashingPrice { get; set; }
        public Nullable<decimal> RentPrice { get; set; }
    }
}
