//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public string ID { get; set; }
        public string InvNo { get; set; }
        public short InvType { get; set; }
        public Nullable<short> InvSubType { get; set; }
        public short DataType { get; set; }
        public int HotelID { get; set; }
        public int RegionID { get; set; }
        public short InvState { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> TaskType { get; set; }
        public string Remrak { get; set; }
        public int CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> UpdateUserID { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string MacCode { get; set; }
        public short Comfirmed { get; set; }
        public bool Processed { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<int> ConfirmUserID { get; set; }
        public string ConfirmUserName { get; set; }
        public short PaymentStatus { get; set; }
    }
}
