//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_right
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_right()
        {
            this.sys_right_button = new HashSet<sys_right_button>();
        }
    
        public int RightID { get; set; }
        public string RightCode { get; set; }
        public Nullable<int> RightParentID { get; set; }
        public string RightName { get; set; }
        public Nullable<int> RightSort { get; set; }
        public string RightUrl { get; set; }
        public string RightIcon { get; set; }
        public Nullable<int> RightType { get; set; }
        public Nullable<bool> ShowInMainMenu { get; set; }
        public int ApplicationID { get; set; }
    
        public virtual sys_application sys_application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_right_button> sys_right_button { get; set; }
    }
}
