//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class goodsorder
    {
        public string ID { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserID { get; set; }
        public int HotelID { get; set; }
        public int TotalQuantity { get; set; }
        public decimal TotalMoney { get; set; }
        public short OrderState { get; set; }
        public short PaymentType { get; set; }
        public Nullable<int> ComfirmUserID { get; set; }
        public Nullable<System.DateTime> ComfirmTime { get; set; }
        public string Remarks { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<System.DateTime> DistributionTime { get; set; }
        public Nullable<System.DateTime> SignTime { get; set; }
        public string Distributor { get; set; }
        public string DistributorTel { get; set; }
    }
}
