//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int ID { get; set; }
        public int RegionID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public short InvType { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> SizeID { get; set; }
        public int TextileCount { get; set; }
        public int TextileTotal { get; set; }
    }
}
