//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_privilege
    {
        public int PrivilegeID { get; set; }
        public string PrivilegeMaster { get; set; }
        public Nullable<int> PrivilegeMasterValue { get; set; }
        public string PrivilegeAccess { get; set; }
        public Nullable<int> PrivilegeAccessValue { get; set; }
        public Nullable<bool> PrivilegeOperation { get; set; }
    }
}
