//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETexsys.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain
    {
        public string ID { get; set; }
        public System.DateTime HappenTime { get; set; }
        public string Cause { get; set; }
        public string Remarks { get; set; }
        public int UserID { get; set; }
        public int HotelID { get; set; }
        public bool Comfirmed { get; set; }
        public Nullable<int> ComfirmUserID { get; set; }
        public Nullable<System.DateTime> ComfirmTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
